### ISSUE TITLE
[ISSUE] check_static_ip method error out

### ISSUE THREAD

**Issue by gopurx** [zscaler/zscaler-sdk-python#168]
**Description**
While trying to utilize check_static_ip method, it results stack trace.

**Reproduction**
`print(zia.traffic.check_static_ip(ip_address='203.0.113.11'))`
```
-------------------------------------------------------------------
Traceback (most recent call last):
  File "/zscaler/venv/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
  File "/zscaler/zscaler_ops_sdk.py", line 23, in <module>
    print(zia.traffic.check_static_ip(ip_address='203.0.113.11'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zscaler/venv/lib/python3.12/site-packages/zscaler/zia/traffic.py", line 526, in check_static_ip
    response = self.rest.post("staticIP/validate", json=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zscaler/venv/lib/python3.12/site-packages/zscaler/zia/__init__.py", line 390, in post
    formatted_resp = format_json_response(resp, box_attrs=dict())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zscaler/venv/lib/python3.12/site-packages/zscaler/utils.py", line 288, in format_json_response
    data = convert_keys_to_snake(response.json())
                                 ^^^^^^^^^^^^^^^
  File "/zscaler/venv/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
Return a boolean True/False

**Is it a regression?**
Tried 0.9.3, 0.9.2,0.9.0,0.8.0,0.7.0

**Debug Logs**

**Other Information**
 - OS: macOS
 - Version: Python 3.12.5

**Additional context**

**Comment by willguibr** [comment]
@gopurx Issue has been fixed in the latest minor release v0.9.4
Zscaler DevRel
